### ISSUE TITLE
where is cardinality in your code in resnext

### ISSUE THREAD

**Issue by tengshaofeng** [StickCui/PyTorch-SE-ResNet#1]

**Comment by StickCui** [comment]
Thanks for attention.
There is a mistake for ResNeXt in my implement. You can reference [this version](https://github.com/last-one/tools/blob/master/pytorch/SE-ResNeXt/SeResNeXt.py)  implemented by my classmate.
I am sorry for that mistake.

**Comment by tengshaofeng** [comment]
em, se_resnet is ok. yes?

**Comment by StickCui** [comment]
Yes, there is just a little of components added in resnet.

**Comment by tengshaofeng** [comment]
ok, thanks
